// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Auth.proto

#include "Auth.pb.h"
#include "Auth.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace AuthService {

static const char* services_method_names[] = {
  "/AuthService.services/Login",
};

std::unique_ptr< services::Stub> services::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< services::Stub> stub(new services::Stub(channel, options));
  return stub;
}

services::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(services_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status services::Stub::Login(::grpc::ClientContext* context, const ::AuthService::Credentials& request, ::AuthService::Auth_Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AuthService::Credentials, ::AuthService::Auth_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void services::Stub::async::Login(::grpc::ClientContext* context, const ::AuthService::Credentials* request, ::AuthService::Auth_Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AuthService::Credentials, ::AuthService::Auth_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void services::Stub::async::Login(::grpc::ClientContext* context, const ::AuthService::Credentials* request, ::AuthService::Auth_Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AuthService::Auth_Response>* services::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::AuthService::Credentials& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AuthService::Auth_Response, ::AuthService::Credentials, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AuthService::Auth_Response>* services::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::AuthService::Credentials& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

services::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      services_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< services::Service, ::AuthService::Credentials, ::AuthService::Auth_Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](services::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AuthService::Credentials* req,
             ::AuthService::Auth_Response* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

services::Service::~Service() {
}

::grpc::Status services::Service::Login(::grpc::ServerContext* context, const ::AuthService::Credentials* request, ::AuthService::Auth_Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace AuthService
#include <grpcpp/ports_undef.inc>

